name: CI

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    # permissions:
    #   contents: read
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Define dependencies
        run: |
          echo "mkdocs-material~=9.0" >> requirements.txt

      - name: Setup runtime environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip

      - name: Update package manager
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build artifact
        run: mkdocs build --strict --site-dir build/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # permissions:
    #   contents: read
    #   id-token: write
    #   pages: write
    steps:
      - name: Retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: _site/

      - name: Prepare deployment
        uses: actions/upload-pages-artifact@v2

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v2
